spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      how-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

#Debug
logging:
  level:
    org.springframework.web: DEBUG
